### ISSUE TITLE
Need 128 commits to get max brightness in contribution graph

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/github-unwrapped-2023#117]
I believe

It should take the highest count of the user of the year

**Comment by MehmetAdemi** [comment]
quite a low contrast for users like me

![Screenshot 2023-12-08 at 19 37 25](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/6fdc3515-d1fd-49c4-a642-6edc53800ae4)

**Comment by JonnyBurger** [comment]
fixed
