### ISSUE TITLE
Landing page - banner, use assets/icons to explain Remotion's approach

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/github-unwrapped-2023#12]
It would be nice to show Remotion's benefits for those devs that don't know about Remotion (e.g. personalization, statistics/data, shareable MP4 video)

What I mean here is shown in the following:
![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/e41d7e0b-6b46-4045-b890-d8de98ec1a44)

**Comment by JonnyBurger** [comment]
Those are not really Remotion benefits, but a product description - we had them but removed them because we couldn't fit it in the design

**Comment by JonnyBurger** [comment]
@MehmetAdemi Do we have a space to do more Remotion advertising in the about page?

**Comment by MehmetAdemi** [comment]
@JonnyBurger, I like the idea of using an illustrated product description on the About page. 
The current state is the following. If you don't mind, I would rearrange those text boxes. After the re-arrangement, we might have space to insert an illustrated product description (i.e., Remotion promotion).

Is it OK?


![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/c1aaf816-11a8-4149-8808-02a178ac3a3f)

**Comment by MehmetAdemi** [comment]
I would suggest this arrangement below. And to avoid an overload of information, I wouldn't add an illustrated product description. Instead, I would use two banners for the README; 
one for GitHub Unwrapped, and 
the other as an illustrated product description of Remotion based on the campaign. 

This would also lead to the issue/task #48 


![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/3e582c06-2f53-473c-aae5-48a7b227bd3c)

**Comment by MehmetAdemi** [comment]
@JonnyBurger,  also, can you tell me where I find the created assets for the illustrated product description? 
Don't see them in the Figma storyboard.

**Comment by MehmetAdemi** [comment]
After discussing with Jonny, we are not going to show an illustrated product description anywhere. There was such a description but it has been deleted, bc. we thought it didn't match the design vision.

I'm going to close this issue and mark the task as "done". Also going to do the re-arrangement of the About page.

Here is what we had before and deleted:

![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/df0e9742-ec09-4d3d-9e81-41b82354400b)
