### ISSUE TITLE
Bad contrast for text (i.e., programming language name)

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/github-unwrapped-2023#131]
For the following user, we get a bad contrast for the programming language "reStructuredText"

User: https://staging.githubunwrapped.com/gvanrossum

![Screenshot 2023-12-11 at 11 04 35](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/8d86c874-d4c5-4d0a-8376-5fab13f1522b)

**Comment by JonnyBurger** [comment]
Fixed in 1be4a024978947ed2c479a1a73467582739df3af
