### ISSUE TITLE
Replace Octocat on mobile view

### ISSUE THREAD

**Issue by maria-paul** [remotion-dev/github-unwrapped-2023#134]
These are the old octocat's colours. The new cat svg is on the drive under "Video-Page".

![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/73991323/5c4bbc77-ff8a-4db8-9516-2ce5cd25ce19)

**Comment by MehmetAdemi** [comment]
Here is the SVG @maria-paul is talking about (just right-click and download):


![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/52423b4a-20da-4d77-af10-0f24bc8779cc)

**Comment by MehmetAdemi** [comment]
should be done with PR: #159
