### ISSUE TITLE
About page - prepare content

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/github-unwrapped-2023#14]
Last year's About page: https://github.com/remotion-dev/github-unwrapped-2022/blob/main/src/components/FaqPage.tsx

![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/b29768ba-d7c0-4504-aa27-a99cf90c91f7)

**Comment by MehmetAdemi** [comment]
Changes to last year's About page:

### Who is behind the #GitHubUnwrapped?
The project was implemented by [Remotion](https://www.remotion.dev/) in collaboration with [ForOneRed](https://www.foronered.com/). ForOneRed was also responsible for the design of this project.


### You can host a Year in Review for your users!
Want to give your users their personalized video at the end of 2024?

Developers: Check out [Remotion](https://remotion.dev/) and the source code [of this project!](https://github.com/remotion-dev/github-unwrapped-2023)

Non-developers: Drop your email and we'll contact you in September 2024 for a free consultation!

### Credits
Music - [Robots](https://audiojungle.net/item/robots/35287595) by Nicolas T.
Design - [ForOneRed](https://www.foronered.com/)
Font - [Mona Sans](https://github.com/github/mona-sans) by GitHub
Libraries - [Next.js](https://github.com/vercel/next.js)

**Comment by MehmetAdemi** [comment]
@JonnyBurger, does this still apply for 2023?
<img src="https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/dfcf4f87-b83c-4966-b109-51eb2a5f1181" width=50% height=50%>

**Comment by JonnyBurger** [comment]
@MehmetAdemi Yes!
