### ISSUE TITLE
add number of contributions graph

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/github-unwrapped-2023#143]
@JonnyBurger 

It would be nice to have a number next to the contributions graph since this is going to make some impressions or is funny to talk about. Currently, there is none, however I used to see a number a while ago. 

![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/baf0c6be-8344-4bdc-8318-66332357a18a)

![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/70b47cba-1420-405c-8692-6bf2e0052b0a)

**Comment by JonnyBurger** [comment]
Luke is working on this!

**Comment by lukezirngibl** [comment]
done
