### ISSUE TITLE
Landing page - "Team" section

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/github-unwrapped-2023#18]
It would be nice to have a "Team" section, where people can find a behind-the-scene gallery and team introduction. 
This can serve to give credits to ForOneRed. 

If we want to do this then please open new tasks like:
Team section - design
Team section - implementation

Alternatively, we can incl. this in the "About" page. Curious to know your thoughts on this.

![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/d9d238b4-c021-4bfc-ab96-bfb8820e549b)

**Comment by lukezirngibl** [comment]
@MehmetAdemi will include in About
