### ISSUE TITLE
Incorrect Merged PR

### ISSUE THREAD

**Issue by AmoDinho** [remotion-dev/github-unwrapped-2023#184]
The unwrapped is saying I have only 1 merged PR, which is totally incorrect. 

I at least do 2 a day minimum.

<img width="1090" alt="Screenshot 2023-12-14 at 11 34 52" src="https://github.com/remotion-dev/github-unwrapped-2023/assets/19347140/f4a6df38-b842-40ce-8bc8-5912ccc2e5a1">

**Comment by JonnyBurger** [comment]
It seems like those merged pull requests are not publicly visible - if you want private activity to be included, see here! https://githubunwrapped.com/about#private-activity
