### ISSUE TITLE
Landing page - "Sign in with GitHub" link, check for its contrast and functionality

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/github-unwrapped-2023#20]
On some occasions, it seems like once you click the link, the font becomes dark blue, and the contract becomes bad. 

![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/bb30bd9f-aa02-4148-b732-20747dc3b18c)

**Comment by MehmetAdemi** [comment]
@matteo-gamba, were you able to reproduce this issue?

**Comment by JonnyBurger** [comment]
I could not reproduce it on staging anymore. Seems fine to me.
