### ISSUE TITLE
Landing page - background, animated rocket ship in the background

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/github-unwrapped-2023#22]
A rocket ship flying in the background would be nice. But It might get busy in the background again. Curious to know your thoughts on this.

![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/22a6e8a6-dc6e-41a4-9b8e-40102041bd17)

**Comment by JonnyBurger** [comment]
We decidec to skip it this year, sorry
