### ISSUE TITLE
Video player - add a play button for the video

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/github-unwrapped-2023#23]
We might even want to add an animation when the button gets clicked.
![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/721db8c3-6af5-45e8-85e1-1e08d6854d53)

Currently, there is no button at all:
![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/d4666f9c-4f4c-4b61-b93c-0c5601d3ce71)

**Comment by JonnyBurger** [comment]
Let's put the play button designed by Isi there

**Comment by JonnyBurger** [comment]
Design is now in Figma

Make the button a bit smaller than it currently is

**Comment by MehmetAdemi** [comment]
I'm not sure, do you want me to do this?
If so, are you talking about this asset?
![Screenshot 2023-12-06 at 15 14 39](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/964ac580-a989-421b-bc42-752b89f0abee)
