### ISSUE TITLE
Music & Licences

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/github-unwrapped-2023#30]
We either go for a given song on a platform (i.e., Envato Market's Audio Jungle or Epidemicsound) or create one via commission on Fiverr or Upwork.

**Comment by MehmetAdemi** [comment]
Epidemic Sound, Single track license: https://www.epidemicsound.com/single-track-pricing/

**Comment by MehmetAdemi** [comment]
Envato Market, with its branch product AudioJungle, offers a better license option than Epidemic Sound. Going with AudioJungle we will have to go for the Music Mass Reproduction license (i.e., USD 216). Envato Market even offers commercial use licenses within their subscription (they have only one subscription plan, i.e., USD 16.50 per month). 


AudioJungle licensing: https://audiojungle.net/licenses/music?license=music_mass_reproduction
![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/0aae2cb2-3ff9-44ff-ad04-647136936d57)

Envato Element (i.e., Envato Market) licensing: https://elements.envato.com/license-terms
![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/b43c805c-8de7-43a4-a75a-2d131109c9c6)

**Comment by MehmetAdemi** [comment]
However, I'm still struggling to find good and fitting music. My favorite so far:

1. https://audiojungle.net/item/that-hiphop/18468055
2. This one would be quite funny since it is well-known: https://elements.envato.com/rossini-william-tell-overture-NH8GCT3
3. https://audiojungle.net/item/motivational-hiphop/20897893
4. One part of this would be nice for the intro before the rocket launch, 1:20 - 1:30: https://elements.envato.com/space-journey-KYXGL92
5. https://elements.envato.com/hip-hop-positive-Q2FMUZA
6. This one only would make sense if we would sync the video to the audio: https://elements.envato.com/boom-bap-positive-X3JT43H

**Comment by JonnyBurger** [comment]
I like this one: https://audiojungle.net/item/robots/35287595

**Comment by MehmetAdemi** [comment]
> I like this one: https://audiojungle.net/item/robots/35287595

I like this too. I'm going to purchase the Music Mass Reproduction, which should cover the campaign more than enough (i.e., USD 79).

![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/ea09f1aa-e62d-4cd1-86d6-d4c0db016a24)

**Comment by JonnyBurger** [comment]
@MehmetAdemi The author offers audio editing. How about we offer to buy the most expensive one ($300) if he sends us the source file? Then we can trim, remove instruments, change BPM to better fit it for us

**Comment by MehmetAdemi** [comment]
I'll email the author and ask if we can agree on this.

**Comment by MehmetAdemi** [comment]
@JonnyBurger, In case we need sound effects, I would suggest going for Epidemic Sounds since we are going to upgrade the license there.

**Comment by maria-paul** [comment]
I'd say that using sound effects will really pull it together and bring it to life!

**Comment by MehmetAdemi** [comment]
Sound effects can be found here (preferably): https://www.epidemicsound.com/sound-effects/

Alternatively: 
- https://audiojungle.net/category/sound
- https://elements.envato.com/sound-effects

**Comment by JonnyBurger** [comment]
Let's license from SmartSound only.
If you use a sound or music, write in https://github.com/remotion-dev/github-unwrapped-2023/issues/87
