### ISSUE TITLE
Sponsorships animation

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/github-unwrapped-2023#33]

**Comment by MehmetAdemi** [comment]
@lukezirngibl, this issue has been opened up by you. I'm just curious, are we going to add sponsorships to GitHub Unwrapped? This is nice since orgs could perhaps do a video as well, but perhaps I'm getting sth. wrong here and it meant for the users that get sponsors. (cc @JonnyBurger )

**Comment by JonnyBurger** [comment]
It is meant for users that sponsor other users

**Comment by MehmetAdemi** [comment]
@JonnyBurger, @lukezirngibl and @matteo-gamba 

Thanks for explaining. Is someone already working on this? Or can we mark it as "todo", so one of you devs can pick it up?

**Comment by JonnyBurger** [comment]
We currently see it as an optional scene, if we have enough time, we will tackle it.

So we can currently leave it unassigned
