### ISSUE TITLE
About page - implementation

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/github-unwrapped-2023#35]
Red marked sections need to be updated.

Last year's "About" page: https://github.com/remotion-dev/github-unwrapped-2022/blob/main/src/components/FaqPage.tsx
![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/b29768ba-d7c0-4504-aa27-a99cf90c91f7)

**Comment by MehmetAdemi** [comment]
Changes to last year's About page:

### Who is behind the #GitHubUnwrapped?
The project was implemented by [Remotion](https://www.remotion.dev/) in collaboration with [ForOneRed](https://www.foronered.com/). ForOneRed was also responsible for the design of this project.


### You can host a Year in Review for your users!
Want to give your users their personalized video at the end of 2024?

Developers: Check out [Remotion](https://remotion.dev/) and the source code [of this project!](https://github.com/remotion-dev/github-unwrapped-2023)

Non-developers: Drop your email and we'll contact you in September 2024 for a free consultation!

### Credits
Music - [Robots](https://audiojungle.net/item/robots/35287595) by Nicolas T.
Design - [ForOneRed](https://www.foronered.com/)
Font - [Mona Sans](https://github.com/github/mona-sans) by GitHub
Libraries - [Next.js](https://github.com/vercel/next.js)

**Comment by maria-paul** [comment]
Can we please replace the image on the right? 

![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/73991323/b5618de9-75bd-4dde-9dbe-232b2b641680)

Replace it with this image (its on figma, on top of the "about page" frame):

![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/73991323/155b7f8a-c4ec-4b83-bb88-0f61010cb47f)

**Comment by MehmetAdemi** [comment]
@maria-paul, sure I'll do it quickly

**Comment by MehmetAdemi** [comment]
done: https://staging.githubunwrapped.com/about
