### ISSUE TITLE
No anchor the panel at the bottom

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/github-unwrapped-2023#37]
Feedback from GitHub

> Anchoring the UI to the bottom of the page is awkward on larger screens. Probably best to ditch the octocat holding the UI gag, and center the UI in the screen, and just have the octocat standing on the planet below, anchored to the bottom of the screen. This is what it looks like currently on my larger monitor:

![Screenshot 2023-11-27 at 08 29 36](https://github.com/remotion-dev/github-unwrapped-2023/assets/1629785/2b9bed48-5edc-46fb-8675-9ed803d77825)

**Comment by MehmetAdemi** [comment]
I also agree on this feedback.
