### ISSUE TITLE
Spaceship Redesign

### ISSUE THREAD

**Issue by maria-paul** [remotion-dev/github-unwrapped-2023#43]
A more realistic looking spaceship to match the design language better.
Finalize colors.

**Comment by MehmetAdemi** [comment]
@maria-paul, is there any work left here? Or are we done for now?
Same question for #52 

The task is marked as "done". I'm just asking so I can close or leave the issue open. :)

**Comment by maria-paul** [comment]
For the spaceship, we haven't landed on a final color so i would say don't close it yet.
For the golden planet design-wise its done yes :)

**Comment by MehmetAdemi** [comment]
Thanks for the update! I marked this task as "in progress" again. Once you are done with the color change you can mark as "done" and close the issue. 😊

Issue #52 has been closed.

**Comment by maria-paul** [comment]
Thank you @MehmetAdemi. Yup will do that :)

**Comment by maria-paul** [comment]
We have 3 different rocket colors the user can choose from.
