### ISSUE TITLE
Add pagination for starred repos and sponsored ones

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/github-unwrapped-2023#44]
Right now it is this:

```
}
starredRepositories(first:100, f firstorderBy: {field: STARRED_AT, direction: DESC}) {
	edges {
		starredAt
		cursor
		node {
			name
			owner {
				login
			}
		}
	}
}
sponsoring(first: 100) {
	nodes {
		... on  Organization {
					login
				}
		... on User {
			login
		}
	}
}
```

Problem 1: Not filtering out those not from 2023
Problem 2: If more than 100, it will not fetch them

**Comment by lukezirngibl** [comment]
We decided to drop sponsorships. But, do we still want to add pagination for the stars? 

Are we animating all the stars and/or showing the repos/# of starts?

@JonnyBurger

**Comment by JonnyBurger** [comment]
We still need to paginate stars - also it doesn't filter for 2023

this leads to a bug currently of me showing that i starred 100 repos in 2023 which is most likely wrong

**Comment by JonnyBurger** [comment]
the animation for stars is now final, we don't show everything, but show the total number of stars
