### ISSUE TITLE
Create dyanmic og:image for user page

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/github-unwrapped-2023#47]

**Comment by MehmetAdemi** [comment]
@JonnyBurger, can you specify what you mean exactly? Is this a dev task?

**Comment by JonnyBurger** [comment]
Yeah, just inserting the tag to the page. The asset Isi will create

**Comment by MehmetAdemi** [comment]
Alright, then I assume this issue waits for the following task to be done: #46

**Comment by MehmetAdemi** [comment]
@JonnyBurger, can we consider this task/issue as done?

**Comment by JonnyBurger** [comment]
Only now! But yes
