### ISSUE TITLE
Write README.md for 2023

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/github-unwrapped-2023#49]
@MehmetAdemi Can you copy the README from last year https://github.com/remotion-dev/github-unwrapped-2022/blob/main/README.md into this year and review the content for this year? Make adjustments or remove stuff that does not apply this year.

Does not have to be perfect for now and does not need to contain images (@IsabellF will create those)

**Comment by MehmetAdemi** [comment]
For sure, will create a first draft by the end of today.

**Comment by MehmetAdemi** [comment]
Here is the PR: https://github.com/remotion-dev/github-unwrapped-2023/pull/55

Once the og:image for the landing page (#46) is done. I'll add those assets to the README.
