### ISSUE TITLE
Share page

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/github-unwrapped-2023#50]
This page should display a button to download the video and explain:

- Download your video
- Click this button to open Tweet composer
- Drag it into Twitter
- Send

**Comment by MehmetAdemi** [comment]
Not sure, how we are going to do the sharing via X/Twitter. But in case we are going to do it like last year could we approach it this year with writing instructions like this?

![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/2c485bbd-ce49-4e64-b41f-e9a5233158f8)

**Comment by MehmetAdemi** [comment]
Associated PR is this one: #140
