### ISSUE TITLE
Language planets

### ISSUE THREAD

**Issue by turelc** [remotion-dev/github-unwrapped-2023#56]
Illustrations for:

- [x] Ruby
- [x] C++
- [x] Placeholder grey

**Comment by MehmetAdemi** [comment]
@turelc, are there any other language planets being added here? Or do we have enough now?

The task is marked as "done". I'm just asking so I can close or leave the issue open. :)
Same question for #59

**Comment by turelc** [comment]
I finished designing the planets and won't work on more atm, we should have enough- but in case anybody has improvements or changes I can reopen the issue as a reminder to edit them, right? 59 is also done on my side unless there is more feedback/changes tbd

**Comment by MehmetAdemi** [comment]
Yes, you got it right. I would suggest let's close them, and if those tasks/issues should come up again, we can reopen the issue and mark the tasks from "done" back to "todo" or "in progress".  Thanks!
