### ISSUE TITLE
Dashboard radar asset

### ISSUE THREAD

**Issue by turelc** [remotion-dev/github-unwrapped-2023#60]
Create assed for PRs merged scene (radar and diagrams)

- [ ] Design radar
- [ ] Design radar elements
- [x] Globe
- [x] Graph
- [x] Wave
- [x] Circle graph
- [ ] Animate radar
- [ ] 3 days until... layout

**Comment by JonnyBurger** [comment]
@turelc I can we put the PRs merged scene on the bottom right scene?

![image](https://github.com/remotion-dev/github-unwrapped-2023/assets/1629785/88b9720d-13b1-43e8-aa49-b13d0ade2e2a)


Is the plan to add some overlay for this?

**Comment by turelc** [comment]
Yess you can use them to put overlays on. Otherwise I can also make the left one darker so it does not stick out as much.

**Comment by JonnyBurger** [comment]
@turelc Awesome! I can do that myself, will be easier than to re-import the SVG
