### ISSUE TITLE
User must set "Show private contributions to true" and then re-fetch the data

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/github-unwrapped-2023#62]
We should explain this in the FAQ

**Comment by MehmetAdemi** [comment]
This seems to be done, right? Can we close this issue/task?

![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/929c30a8-29f5-4ae0-91fb-5f970aada00c)

**Comment by MehmetAdemi** [comment]
@JonnyBurger, does this task/issue still need sth., or is it done?

**Comment by JonnyBurger** [comment]
Yes, done!
