### ISSUE TITLE
Animate rocket fire

### ISSUE THREAD

**Issue by turelc** [remotion-dev/github-unwrapped-2023#63]
Animate fire for rocket in scenes with small rocket

- [ ] Asset
- [ ] Animate

**Comment by JonnyBurger** [comment]
@turelc You don't have to do it anymore, we have found assets for it that we licensed!

<img width="1205" alt="image" src="https://github.com/remotion-dev/github-unwrapped-2023/assets/1629785/78dd8590-0063-462e-a9ab-82c490024dca">
