### ISSUE TITLE
Rendering

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/github-unwrapped-2023#69]
I need to implement rendering 🙈

**Comment by MehmetAdemi** [comment]
Just to push you a little bit hahaha
![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/679c0ae5-47ba-4bd7-bde9-5fec470b26d3)

**Comment by JonnyBurger** [comment]
Deploying a version now that is pretty optimized
