### ISSUE TITLE
Icon for the GitHub app

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/github-unwrapped-2023#70]
We have the default app icon when you login with GitHub

**Comment by MehmetAdemi** [comment]
@JonnyBurger are you referring to this? If so, then I assume this is a dev task? 

![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/9d089e1c-602e-4420-a719-67625106a54a)

**Comment by JonnyBurger** [comment]
Yes!

**Comment by MehmetAdemi** [comment]
Unfortunately I don't know how to change this.
Can @matteo-gamba do this?

**Comment by JonnyBurger** [comment]
No, we will create a GitHub app on remotion-dev. Actually it should use that on staging.githubunwrapped.com! i assume you are on the local version?

**Comment by MehmetAdemi** [comment]
Does this work? If so, can you mark is as done and close the issue? If not, what else needs to be done?
![Screenshot 2023-12-05 at 13 50 24](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/b6a81506-aa19-49b3-a752-cf9670d97201)

**Comment by MehmetAdemi** [comment]
More campaign style:

![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/21cb5031-1734-4197-b3bf-575769e276ae)
