### ISSUE TITLE
Blend mode in 404 page is not right

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/github-unwrapped-2023#78]
<img width="688" alt="image" src="https://github.com/remotion-dev/github-unwrapped-2023/assets/1629785/b66f4447-7c93-4f15-874e-484ca1169c93">

It looks a bit different in Figma, on the web the multiply blending mode is not applied correctly

**Comment by MehmetAdemi** [comment]
This is who it looks like in Figma:
![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/08dae6f7-e7a0-4116-8fc0-1ea1ccef007c)

**Comment by MehmetAdemi** [comment]
Tried to fix it, and came up this this result:
Here is the PR #97 

![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/62368d0e-b441-4b94-9c73-7bc15d9b4698)
