### ISSUE TITLE
Golden planet scene

### ISSUE THREAD

**Issue by lukezirngibl** [remotion-dev/github-unwrapped-2023#79]
Sound idea: https://audiojungle.net/item/choir-church/45385903

**Comment by MehmetAdemi** [comment]
Sounds epic!

@JonnyBurger, what do you think about this? Do we want to use different soundtracks? Does it make sense time- and complexity-wise?

**Comment by JonnyBurger** [comment]
@MehmetAdemi We'll do a sound-design which can include multiple tracks.

After todays call I'll make a decision from which provider we will use soundtracks.

**Comment by JonnyBurger** [comment]
Unfortunately I had to remove the choir @lukezirngibl. It does not sound very good compared to letting the spacewave theme run throughout, leads to complications and I also forgot to send it to license since we didn't include it in the audio list :/
