### ISSUE TITLE
Cat is not aligned on landing page anymore

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/github-unwrapped-2023#82]
<img width="1305" alt="image" src="https://github.com/remotion-dev/github-unwrapped-2023/assets/1629785/6a21dda4-084c-43cc-bb68-17ba32349303">

**Comment by MehmetAdemi** [comment]
@JonnyBurger, @lukezirngibl and @matteo-gamba 
Can we simply remove the Octocat once the height of the browser is below 835px?

![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/9986cd2d-a608-45ff-8022-3d53257c0bac)



![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/117be6bb-ad2e-44b1-9f95-8502fd801d82)



![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/2fb76ff9-802e-47ba-a991-e879501d2694)

**Comment by MehmetAdemi** [comment]
I tried to solve this myself. Appreciate any feedback here: #99

**Comment by MehmetAdemi** [comment]
This task and issue has been finally resolved with PR #104
