### ISSUE TITLE
License sounds and send

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/github-unwrapped-2023#87]
**Up to 5 music tracks**

**Up to 15 SFX**
1. ATMO PADS Choir Pad 01 (Luke)
2. IMPACT STONE Rockfall Glass Single 07 (Jonny)
3. IMPACT STONE Rockfall Glass Single 04 (Jonny)
4. IMPACT STONE Rockfall Glass Single 01 (Jonny)
5. SCI FI DEVICE Laser Welder Short 01 (Jonny)
6. SCI FI SPACE Laser Gun Double Shot 01 (Jonny)
7. SCI FI SPACE Laser Gun Double Shot Empty 01 (Jonny)
8. SCI FI SPACESHIP Medium 03 Exterior Start Departure Fast 0 (Jonny)
9. UI Modern Large List Tonal Bleep Decelerate Long 02 (Jonny)

Once we decided we will send them to Pierre (Smartsound) and he'll invoice us for €1000 probably

**Comment by MehmetAdemi** [comment]
Updated list:

**Sound effects:**
SCI-FI SPACESHIP Medium 03 Exterior Start Departure Fast 01
CINEMATIC IMPACT Airy Hit 01
CINEMATIC WHOOSH Small Hover Pass By 02
SCI-FI SPACESHIP Medium 03 Exterior Flyby Fast Close 01
CINEMATIC WHOOSH Wind Gust Medium 02
CINEMATIC WHOOSH Small Hover Pass By 02
CINEMATIC-IMPACT-Wham-20
MAGIC ARCANE Projectile Shot Impactful 01
SCI FI DRONE Spaceship Turbine Exterior 02
UI NOTIFICATION Glockenspiel Single High 01
UI Modern Large List Tonal Bleep Decelerate Long 02
UI BUTTON Small Generic 03
CINEMATIC SWELL Magical Chord Reversed 01
UI-Feedback-Modern-Weigh-Options-Single-02
FOLEY-GAMING-Gaming-Mouse-Wheel-Scroll-Smooth-01
MAGIC-HOLY-Angelic-Pearly-Shimmer-03
SCI-FI SPACESHIP Medium 03 Exterior Arrival Landing Fast 01


**Music:**
Infinity
Fury
Space Cowboy

**Comment by JonnyBurger** [comment]
I sent, we just need to pay the invoice once it comes
