### ISSUE TITLE
Design Check by GitHub

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/github-unwrapped-2023#9]
Let Octocat designs be checked by GitHub design team.
There are community designs for Octocats, it might be of use: https://octodex.github.com/

**Comment by MehmetAdemi** [comment]
@JonnyBurger, are there any design checks with GitHub? Can we close the issue, since the task in the Kanban has already been marked as "done"?

**Comment by JonnyBurger** [comment]
We did the review of the Octocats, so we should now be brand-safe.

We will for sure still get design feedback in some bilateral discussions, but no action remaining.

**Comment by MehmetAdemi** [comment]
Alright, since there is no action remaining, can we close this issue and reopen it in case there are any actions required?
