### ISSUE TITLE
Are the contributions right?

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/github-unwrapped-2023#96]
Why is it an array of 364?
Why not 365?

How do we handle the days not yet passed in the year?

**Comment by lukezirngibl** [comment]
@JonnyBurger - 364 was probably a WIP change during development

Days not yet passed in the year will have 0 contributions. 

Numbers/data looks right too me. Have you seen any inconsistencies?

**Comment by JonnyBurger** [comment]
Ok, sounds good to me! We can bump to 365 and then close it.

**Comment by lukezirngibl** [comment]
ooh, now i remember. 364 is divisible by 7...

**Comment by JonnyBurger** [comment]
oh, good idea let's keep it then
